import dns from "node:dns"
dns.setServers(["8.8.8.8", "8.8.4.4"])


import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";





export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poopins =Poppins({
 variable:"--font-poopins",
 subsets:["latin"],
 weight:["400","500","600","700"]
})
export const montserrat =Montserrat({
 variable:"--font-montserrat",
 subsets:["latin"],
 weight:["400","500","600","700"]
})

export default function RootLayout({ children }) {
  return (
    <html
      data-theme='light'
      lang="en"
      className={` h-full antialiased`}
    >
      <body className= {`${poopins.className} min-h-full flex flex-col`}>
       
        <main>{children}</main>
        
        </body>
    </html>
  );
}
